### ISSUE TITLE
def getEveryDigits(img, squares)

### ISSUE THREAD

**Issue by thebeginner6** [UtkuGlsvn/sudokusolver#8]
Hi 

I get an error when using this def getEveryDigits(img, squares):

window = img2[x1:x2, y1:y2] that shows me the following error window = img2[x1:x2, y1:y2]

What can i do here?

**Comment by UtkuGlsvn** [comment]
Hello,

Can you write a more descriptive error, are you getting a syntax error?

**Comment by thebeginner6** [comment]
Hi

Thanks for your quick response :D

First i got this Error
Traceback (most recent call last):
File "C:/Users/Claudio/Documents/FHNW/Bver/Sudoku/sudokusolver-master/
main.py
<https://www.youtube.com/redirect?q=http%3A%2F%2Fmain.py%2F&stzid=UgwfrnRFacfh7Z5pKgV4AaABAg&redir_token=1PUeiXQiyH6xr9JKFomLzhYcRjR8MTU3Nzc0MjY4MUAxNTc3NjU2Mjgx&event=comments>",
line 230, in <module> corners = findCorners(processed) File
"C:/Users/Claudio/Documents/FHNW/Bver/Sudoku/sudokusolver-master/main.py
<https://www.youtube.com/redirect?q=http%3A%2F%2Fmain.py%2F&stzid=UgwfrnRFacfh7Z5pKgV4AaABAg&redir_token=1PUeiXQiyH6xr9JKFomLzhYcRjR8MTU3Nzc0MjY4MUAxNTc3NjU2Mjgx&event=comments>",
line 43, in findCorners h, contours, hierarchy =
cv2.findContours(processed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE) ValueError:
not enough values to unpack (expected 3, got 2)

I think i have the python 3.7 version.

I then removed the h from this line:

    h, contours, hierarchy = cv2.findContours(processed, cv2.RETR_LIST,
cv2.CHAIN_APPROX_SIMPLE)

and it worked. But i got a new Error which i don't know how to solve:

Traceback (most recent call last):
  File "C:\Users\Claudio\PyCharm Community Edition
2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Claudio\PyCharm Community Edition
2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py",
line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File
"C:/Users/Claudio/Documents/FHNW/Bver/Sudoku/sudokusolver-master/main.py",
line 240, in <module>
    old = getEveryDigits(cropped, squares)
  File
"C:/Users/Claudio/Documents/FHNW/Bver/Sudoku/sudokusolver-master/main.py",
line 125, in getEveryDigits
    window = img[x1:x2, y1:y2]
TypeError: 'Image' object is not subscriptable


I also don't really know what this error means. Can you help me out here?

window= img[x1:x2,y1:y2] somehow does some problems but i don't know what i
could do to fix...

What version of python were you using? any idea why i get this errors?

Thanks again you are my hero i was really struggling with this in
university...

Kind Regards

Claudio


Am So., 29. Dez. 2019 um 22:19 Uhr schrieb utku glsvn <
notifications@github.com>:

**Comment by ffahri** [comment]
Hey @thebeginner6 , 
could you please change 
` window=img[x1:x2, y1:y2]`

to  

` window=img2[x1:x2, y1:y2]`
and try again

**Comment by UtkuGlsvn** [comment]
python version 3 fix
